// Pixabay - Vue/src/pages/Home.vue
<template>
  <div id="app">
    <Search v-on:fetchImages="fetchImages" />
    <div class="row justify-content-center container mx-auto p-0">
      <div v-if="this.loading" class="spinner-border text-dark" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <p v-else-if="this.images.length === 0" class="h1">No images</p>

      <ImageCard
        v-else
        v-for="image in images"
        :key="image.id"
        :image="image"
      />
    </div>
  </div>
</template>

<script>
import Search from "../components/Search.vue";
import ImageCard from "../components/ImageCard.vue";

export default {
  name: "Home",
  components: {
    Search,
    ImageCard,
  },
  data() {
    return {
      images: [],
      loading: true,
    };
  },
  methods: {
    async fetchImages(searchTerm = "nature") {
      await fetch(
        `https://pixabay.com/api/?key=17039239-7ccdc3f5c80caa80d628661b2&q=${searchTerm}&image_type=photo&pretty=true`
      )
        .then((res) => res.json())
        .then((data) => {
          this.images = data.hits;
          this.loading = false;
        })
        .catch((err) => console.log(err));
    },
  },
  created() {
    this.fetchImages("business");
  },
};
</script>

<style></style>

// Pixabay - Svelte/src/pages/Home.svelte
<script>
    import { onMount } from "svelte";
    import Search from "../components/Search.svelte";
    import ImageCard from "../components/ImageCard.svelte";

    let images = [];
    let loading = true;
    const PIXABAY_KEY = process.env.PIXABAY_KEY;

    const fetchImages = async (searchTerm = "nature") => {
        await fetch(
            `https://pixabay.com/api/?key=${PIXABAY_KEY}&q=${searchTerm}&image_type=photo&pretty=true`
        )
            .then((res) => res.json())
            .then((data) => {
                images = data.hits;
                loading = false;
            })
            .catch((err) => console.log(err));
    };
    onMount(async () => fetchImages());

    const search = (e) => {
        fetchImages(e.detail);
    };
</script>

<main class="container">
    <Search on:search={search} />

    <div class="row justify-content-center">
        {#if loading}
            <div class="spinner-border text-dark" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        {:else if images.length === 0}
            <p>No images</p>
        {:else}
            {#each images as image}
                <ImageCard {image} />
            {/each}
        {/if}
    </div>
</main>
