// Pixabay - Angular/src/app/components/search/search.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.css'],
})
export class SearchComponent implements OnInit {
  @Output() search: EventEmitter<any> = new EventEmitter();
  searchTerm: string = '';
  constructor() {}

  ngOnInit(): void {}

  onSearch(searchTerm) {
    this.search.emit(searchTerm);
  }
}

<div class="my-5 input-group">
  <input class="form-control" type="text" placeholder="Search for images" [(ngModel)]="searchTerm"
    (keyup.enter)="onSearch(searchTerm)" />
  <div class="input-group-append">
    <button class="btn btn-primary px-5" type="button" (click)="onSearch(searchTerm)">
      Go!
    </button>
  </div>
</div>

// Pixabay - Vue/src/components/Search.vue
<template>
  <div class="container">
    <div class="my-5 input-group">
      <input
        class="form-control"
        type="text"
        placeholder="Search for images"
        v-model="searchTerm"
        @keyup.enter="search"
      />
      <div class="input-group-append">
        <button class="btn px-5" type="button" @click="search">Go!</button>
      </div>
    </div>
  </div>
</template>

<script>
import { mapActions } from "vuex";

export default {
  name: "Search",
  data() {
    return {
      searchTerm: "",
    };
  },
  methods: {
    search() {
      this.$emit("fetchImages", this.searchTerm);
    },
  },
};
</script>


<style scoped>
button {
  background-color: #41b883;
  color: white;
}

button:hover {
  background-color: #46cf92;
  color: #fff;
}
</style>
