// Pixabay - Vue/src/components/Navbar.vue
<template>
  <nav class="navbar navbar-expand-lg shadow-sm">
    <div class="container">
      <router-link to="/" class="navbar-brand logo text-white"
        >Pixabay - Vue</router-link
      >
      <router-link to="/about/" class="navbar-brand logo text-white"
        >About</router-link
      >
    </div>
  </nav>
</template>

<script>
export default {
  name: "Navbar",
};
</script>

<style>
nav {
  background-color: #41b883 !important;
}
</style>

// Pixabay - Svelte/src/components/Navbar.svelte
<script>
    import { Link } from "svelte-routing";
</script>

<style>
    nav {
        background-color: #ff3e00 !important;
    }
</style>

<nav class="navbar navbar-expand-lg bg-primary shadow-sm">
    <div class="container">
        <Link to="/">
            <span class="navbar-brand logo text-white">Pixabay - Svelte</span>
        </Link>
        <Link to="/about/">
            <span class="navbar-brand logo text-white"> About </span>
        </Link>
    </div>
</nav>
