// Pixabay - Vue/src/components/Search.vue
<template>
  <div class="container">
    <div class="my-5 input-group">
      <input
        class="form-control"
        type="text"
        placeholder="Search for images"
        v-model="searchTerm"
        @keyup.enter="search"
      />
      <div class="input-group-append">
        <button class="btn px-5" type="button" @click="search">Go!</button>
      </div>
    </div>
  </div>
</template>

<script>
import { mapActions } from "vuex";

export default {
  name: "Search",
  data() {
    return {
      searchTerm: ""
    };
  },
  methods: {
    ...mapActions(["fetchImages"]),
    search() {
      this.fetchImages(this.searchTerm);
    }
  }
};
</script>


<style scoped>
button {
  background-color: #41b883;
  color: white;
}

button:hover {
  background-color: #46cf92;
  color: #fff;
}
</style>

// Pixabay - Svelte/src/components/Search.svelte
<script>
  import {
    createEventDispatcher
  } from "svelte";
  import {
    onMount
  } from "svelte";


  const dispatch = createEventDispatcher();

  let searchTerm = "";

  const search = () => {
    dispatch("search", searchTerm);
  };
  onMount(async () => {
    document.getElementById("search").addEventListener("keyup", e => {
      if (e.keyCode === 13) {
        search()
      }
    });
  });
</script>

<div class="my-5 input-group">
  <input class="form-control" id="search" type="text" placeholder="Search for images" bind:value={searchTerm} />
  <div class="input-group-append">
    <button class="btn px-5" type="button" on:click={search}>
      Go!
    </button>
  </div>
</div>

<style>
  button {
    background-color: #ff3e00;
    color: white;
  }

  button:hover {
    background-color: #f58560;
    color: #fff;
  }
 
</style>
