// Pixabay - Svelte/src/App.svelte
<script>
    import Navbar from "./components/Navbar.svelte";
    import Home from "./pages/Home.svelte";
    import About from "./pages/About.svelte";
    import { Router, Route } from "svelte-routing";
    export let url = "";
</script>

<Router {url}>
    <Navbar />
    <div class="container">
        <Route path="/" component={Home} />
        <Route path="/about/" component={About} />
    </div>
</Router>

// Pixabay - Vue/src/App.vue
<template>
  <div id="app">
    <Navbar />
    <router-view></router-view>
  </div>
</template>

<script>
import Navbar from "./components/Navbar.vue";
import Home from "./pages/Home.vue";
import About from "./pages/About.vue";


export default {
  name: "App",
  components: {
    Navbar,
    Home,
    About,
  },
};
</script>
