// Pixabay - Svelte/src/pages/About.svelte
<div class="container text-center w-50 mt-5">
    <h1>About us</h1>
    <span>This is an about page</span>
    <hr />
    <p>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et iste
        repellendus velit alias, labore eos sapiente vero maiores aut corporis
        facere! A repudiandae soluta, quod libero voluptate sequi quasi atque
        aliquam mollitia obcaecati cumque ullam quisquam natus ad, quos quaerat
        molestiae perferendis delectus voluptates accusamus. Quis, suscipit.
        Alias, illum culpa. Fugiat voluptatum animi, cum aut, autem illo
        perferendis similique at suscipit enim praesentium consequatur ratione
        possimus odit nisi? Doloribus possimus tenetur ex itaque quod molestiae
        neque quas enim a hic! Assumenda, nostrum ex labore accusantium ad, id
        minima perspiciatis optio magnam accusamus quisquam perferendis est
        eius. Quod rerum quae aperiam?
    </p>
</div>

// Pixabay - Vue/src/pages/About.vue

<template>
  <div class="container text-center w-50 mt-5">
    <h1>About us</h1>
    <span>This is an about page</span>
    <hr />
    <p>
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et iste
      repellendus velit alias, labore eos sapiente vero maiores aut corporis
      facere! A repudiandae soluta, quod libero voluptate sequi quasi atque
      aliquam mollitia obcaecati cumque ullam quisquam natus ad, quos quaerat
      molestiae perferendis delectus voluptates accusamus. Quis, suscipit.
      Alias, illum culpa. Fugiat voluptatum animi, cum aut, autem illo
      perferendis similique at suscipit enim praesentium consequatur ratione
      possimus odit nisi? Doloribus possimus tenetur ex itaque quod molestiae
      neque quas enim a hic! Assumenda, nostrum ex labore accusantium ad, id
      minima perspiciatis optio magnam accusamus quisquam perferendis est eius.
      Quod rerum quae aperiam?
    </p>
  </div>
</template>

<script>
export default {
  name: "About",
};
</script>
