// Pixabay - Angular/src/app/components/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpService } from '../../../services/http.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {
  images: Array<any> = [];
  loading: boolean = true;
  constructor(private http: HttpService) {}

  ngOnInit(): void {
    this.http.getImages().subscribe((obj) => {
      this.images = obj['hits'];
      this.loading = false;
    });
  }

  search(searchTerm) {
    this.http.getImages(searchTerm).subscribe((obj) => {
      this.images = obj['hits'];
      this.loading = false;
    });
  }
}

<div class="container text-center">

  <app-search (search)="search($event)"></app-search>


  <div *ngIf="loading">
    <div class="spinner-border text-dark" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>

  <div *ngIf="images.length === 0 && !loading">
    <p>No images</p>
  </div>

  <div *ngIf="images.length >= 1" class="row justify-content-center">

    <app-image-card *ngFor="let image of images" [image]="image" class="col-sm-6 col-lg-4 mb-4">
    </app-image-card>

  </div>
</div>

// Pixabay - Vue/src/pages/Home.vue
<template>
  <div id="app">
    <Search v-on:fetchImages="fetchImages" />
    <div class="row justify-content-center container mx-auto p-0">
      <div v-if="this.loading" class="spinner-border text-dark" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <p v-else-if="this.images.length === 0" class="h1">No images</p>

      <ImageCard
        v-else
        v-for="image in images"
        :key="image.id"
        :image="image"
      />
    </div>
  </div>
</template>

<script>
import Search from "../components/Search.vue";
import ImageCard from "../components/ImageCard.vue";
import { mapGetters, mapActions } from "vuex";

export default {
  name: "Home",
  components: {
    Search,
    ImageCard,
  },

  methods: {
    ...mapActions(["fetchImages"]),
  },
  computed: mapGetters(["images", "loading"]),

  created() {
    this.fetchImages("business");
  },
};
</script>

<style></style>
